### ISSUE TITLE
Is still extension still maintained? It seems not to work for gmail in Chrome any more.

### ISSUE THREAD

**Issue by StefanRied** [android-police/delete-single-email-extension#12]

**Comment by StefanRied** [comment]
Is still extension still maintained? It seems not to work for gmail in Chrome any more.

**Comment by archon810** [comment]
@StefanRied What doesn't work. I'm still using it every day.

**Comment by StefanRied** [comment]
Thanks for your reply.
I am on a MacOS 11.6 with the current Chrome version.
The extension can be installed in chrome and can be configured as explained.
But it simply never catches any key and never reacts.

**Comment by archon810** [comment]
Hmm, it's working for me in Chrome on Windows. @corbindavenport do you have access to a mac to test this out?

@StefanRied Are you sure you're using the extension correctly, i.e. opening a thread first and only then pressing the key? It's not meant to operate in the list of threads because there's already a keyboard shortcut to delete the whole thread (#).

**Comment by StefanRied** [comment]
Ah, I see. Thanks for the hint. It does actually work on a thread. 
I am so sorry.
I expected it to work on single emails as well.
I know that there are shortcuts, and you can customize shortcuts for deleting single emails.
But there is no way to set the "delete button" to the delete shortcut.

**Comment by archon810** [comment]
Perhaps at some point support for the thread list view can be added so that the shortcut can be customized there as well, but yeah, the primary purpose was to delete individual messages inside threads.

**Comment by StefanRied** [comment]
using Mac-Mail and GMail in parallel for different accounts, I was looking for the same behavior. In Mac Mail, the "delete" or the "backspace" button does delete whatever you mark. A single mail or a thread.
