### ISSUE TITLE
RFE: Support Inbox by GMail

### ISSUE THREAD

**Issue by TPS** [android-police/delete-single-email-extension#5]
#### Expected behavior
Supports [Inbox by GMail](https://www.google.com/inbox/), which I believe to be structurally-similar, but not identical, to GMail proper.

#### Actual behavior
Doesn't 😢 (Can't find way to directly link [G+ post that mentioned that @archon810 doesn't use Inbox, so can't add himself](https://plus.google.com/u/0/+ArtemRussakovskii/posts/JKhNr3Q1q8V?cfem=1))

#### Steps to reproduce the problem
- https://inbox.google.com
- Open any threaded e-mail
- Note no option to delete single e-mail

**Comment by archon810** [comment]
If Inbox doesn't even offer this option, we can't do this. In Gmail, there's an option in the menu that the extension ends up clicking on.

**Comment by TPS** [comment]
That makes sense.  However, since Inbox & GMail proper share the same e-mail account, maybe there's a way to access the function, even if it _doesn't_ show in menu (which I don't see, but I didn't exhaustively search every menu & icon, only the 2 or 3 that made sense to me.)

**Comment by corbindavenport** [comment]
There's a trash button on opened emails in Inbox, we could emulate clicks on that.

**Comment by TPS** [comment]
@corbindavenport But would delete the whole e-mail thread, _not_ an individual message in the thread, which is what this whole extension's about, right?

**Comment by corbindavenport** [comment]
Oh sorry, you are correct, there's no UI element that corresponds to deleting a single email in a thread. I'm not sure if Inbox support would be possible, then.

**Comment by archon810** [comment]
Right, hence my original assessment/comment.

**Comment by archon810** [comment]
Lolclosed.
